[package]
name = "ica-coercer"
version = "0.1.0"
authors = ["Paweł Motyl <pawmot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.12"
shellexpand = "2.0.0"
